[project]
name = "r1-a2a-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk[http-server]>=0.3.1",
    "openai-agents>=0.2.8",
]
