apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: master-mayfly-35959.upstash.io:6379
    - name: redisPassword
      value: AYx3AAIncDEwZTBmZmQ0MWMyN2U0ZTBlOWM5NzVlZjQxMDNiNjk4ZnAxMzU5NTk
    - name: enableTLS
      value: "true"  # Enables secure connection (uses rediss:// protocol)
    - name: actorStateStore
      value: "true"